import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import Cart from '@/components/Cart';

export const metadata: Metadata = {
  title: 'Riz DM',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='min-w-screen min-h-screen flex flex-col items-center'>
        <div className='h-full w-full max-w-[40rem]'>
          <Providers>
            {children}
            <Cart />
          </Providers>
        </div>
      </body>
    </html>
  );
}
